In [9]:
import numpy as np

list vs numpy timetaken


In [15]:
from time import process_time
python_list=[i for i in range(10000)]

start_time=process_time()
python_list=[i+10435939 for i in python_list]

end_time=process_time()

print(end_time-start_time)


0.0


In [16]:
np_array = np.array([i for i in range(10000)])
start_time=process_time()
np_array+=499994

end_time=process_time()
print(end_time-start_time)



0.0


In [19]:
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [20]:
b=np.array([[1,2,3,4]])
print(b)
b.shape

[[1 2 3 4]]


(1, 4)

In [23]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [29]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


math operations on a np array

In [33]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 5 8]
 [0 2 4]
 [2 7 7]]
[[13 15 16]
 [14 18 13]
 [18 16 15]]


In [34]:
print(a+b)

[[17 20 24]
 [14 20 17]
 [20 23 22]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 20 24]
 [14 20 17]
 [20 23 22]]
[[ -9 -10  -8]
 [-14 -16  -9]
 [-16  -9  -8]]
[[ 52  75 128]
 [  0  36  52]
 [ 36 112 105]]
[[0.30769231 0.33333333 0.5       ]
 [0.         0.11111111 0.30769231]
 [0.11111111 0.4375     0.46666667]]


array manupulation

In [37]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 4 1]
 [0 3 7]]
(2, 3)


In [39]:
#transpose

trans=np.transpose(array)
print(trans)
print(trans.shape)

[[4 0]
 [4 3]
 [1 7]]
(3, 2)
